// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAjZ03zf7n35Q7-ZxenKW6J-dsxnHqEo',
    appId: '1:854516815183:web:4858a102fe817760cd613a',
    messagingSenderId: '854516815183',
    projectId: 'abchat-a3e10',
    authDomain: 'abchat-a3e10.firebaseapp.com',
    storageBucket: 'abchat-a3e10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NJFIVIgjJnIoNrl6KUZDC6F-veFPQOU',
    appId: '1:854516815183:android:c1338e152042953ccd613a',
    messagingSenderId: '854516815183',
    projectId: 'abchat-a3e10',
    storageBucket: 'abchat-a3e10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJGgmo2CLHKR_7kWATc3AQU052T5iELg',
    appId: '1:854516815183:ios:951e7d029dd079a1cd613a',
    messagingSenderId: '854516815183',
    projectId: 'abchat-a3e10',
    storageBucket: 'abchat-a3e10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJGgmo2CLHKR_7kWATc3AQU052T5iELg',
    appId: '1:854516815183:ios:951e7d029dd079a1cd613a',
    messagingSenderId: '854516815183',
    projectId: 'abchat-a3e10',
    storageBucket: 'abchat-a3e10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeAjZ03zf7n35Q7-ZxenKW6J-dsxnHqEo',
    appId: '1:854516815183:web:be859d4ffc492ebecd613a',
    messagingSenderId: '854516815183',
    projectId: 'abchat-a3e10',
    authDomain: 'abchat-a3e10.firebaseapp.com',
    storageBucket: 'abchat-a3e10.appspot.com',
  );
}
